export const allProductsData = [
  {
    id: 1,
    img: "/iphone8pBattery.png",
    name: "iPhone 8 Plus Battery",
    price: "550",
    category: "battery",
  },
  {
    id: 2,
    img: "/realme3chargeflex.png",
    name: "Realme 3 Charging Flex",
    price: "250",
    category: "charge flex",
  },
  {
    id: 3,
    img: "/realme3screen.png",
    name: "Realme 3 Screen",
    price: "600",
    category: "screen",
  },
  {
    id: 4,
    img: "/reno5screen.png",
    name: "Reno 5 Screen",
    price: "1200",
    category: "screen",
  },
  {
    id: 5,
    img: "/backcoverMI10.png",
    name: "Back Cover MI 10",
    price: "250",
    category: "back cover",
  },
  {
    id: 6,
    img: "/lensS20ULTRA.png",
    name: "Lens S20 Ultra",
    price: "100",
    category: "other",
  },
  {
    id: 7,
    img: "/usb-c-socket.png",
    name: "USB-C Socket",
    price: "150",
    category: "other",
  },
  {
    id: 8,
    img: "/y7-19screen.png",
    name: "Y7 2019 Screen",
    price: "700",
    category: "screen",
  },
  {
    id: 9,
    img: "/reno10screen.png",
    name: "Reno 10 Screen",
    price: "4000",
    category: "screen",
  },
  {
    id: 10,
    img: "/micro-usb-socket.png",
    name: "Micro USB Socket",
    price: "100",
    category: "other",
  },
  {
    id: 11,
    img: "/iphone8pchargeflex.png",
    name: "iPhone 8 Plus Charge Flex",
    price: "250",
    category: "charge flex",
  },
  {
    id: 12,
    img: "/xsmaxbattery.png",
    name: "iPhone XS Max Battery",
    price: "600",
    category: "battery",
  },
  {
    id: 13,
    img: "/12promaxback.png",
    name: "iPhone 12 PRO MAX Back Glass",
    price: "1000",
    category: "back cover",
  },
  {
    id: 14,
    img: "/powerflex.png",
    name: "Power/Volume Flex",
    price: "150",
    category: "other",
  },
  {
    id: 15,
    img: "/a72-mainflex.png",
    name: "Samsung A72 Main Flex",
    price: "200",
    category: "other",
  },
  {
    id: 16,
    img: "/xscreen.png",
    name: "iPhone X Screen",
    price: "2500",
    category: "screen",
  },
  {
    id: 17,
    img: "/redminote5middleframe.png",
    name: "Redmi Note 5 Middle Frame",
    price: "200",
    category: "other",
  },
  {
    id: 18,
    img: "/xbackglass.png",
    name: "iPhone X Back Glass",
    price: "1000",
    category: "back cover",
  },
  {
    id: 19,
    img: "/nova3ibackglass.png",
    name: "Huawei Nova 3i Back Glass",
    price: "300",
    category: "back cover",
  },
  {
    id: 20,
    img: "/mate10litebattery.png",
    name: "Huawei Mate 10 Lite Battery",
    price: "350",
    category: "battery",
  },
  {
    id: 21,
    img: "/nova3iscreen.png",
    name: "Huawei Nova 3i Screen",
    price: "700",
    category: "screen",
  },
  {
    id: 22,
    img: "/a3sscreen.png",
    name: "OPPO A3S Screen",
    price: "700",
    category: "screen",
  },
  {
    id: 23,
    img: "/xchargeflex.png",
    name: "iPhone X Charging Flex",
    price: "400",
    category: "charge flex",
  },
  {
    id: 24,
    img: "/a02schargeflex.png",
    name: "Samsung A02S Charge Flex",
    price: "150",
    category: "charge flex",
  },
];
